In [12]:
import pandas as pd
df= pd.read_csv('./dataset/Amazon Sale Report.csv',low_memory=False)

In [17]:
df.shape

(128975, 24)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 22.8+ MB

In [14]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [20]:
df[:5]  # similar to df.head(5)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [31]:
type(df['Date'])

pandas.Series

In [32]:
type(df)
df["Date"].shape

(128975,)

In [33]:
df[['Date','Status']].shape

(128975, 2)

In [34]:
df2 = pd.DataFrame(
    {
        "Name": [
            "Braund", "Niroj","Alex"
        ],
        "Age": [22,34,55],
            "Sex": ["male","male","female"]
    }
)

In [35]:
df2["Sex"]

0      male
1      male
2    female
Name: Sex, dtype: str

In [36]:
grade = pd.Series([22,23,265], name="Grade")

In [37]:
grade

0     22
1     23
2    265
Name: Grade, dtype: int64

### syntax
```df.describe()```

In [38]:
# pd.read.csv("data/titanic.csv")
# df.head()

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 22.8+ MB

In [41]:
df['Qty'].unique()

array([ 0,  1,  2, 15,  3,  9, 13,  5,  4,  8])

In [44]:
above3=df[df['Qty'] > 3]
above3.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
937,937,S02-5278980-4327051,04-30-22,Shipped,Amazon,Non-Amazon,Standard,BL017,BL017-63BLACK,Blouse,...,NaN,NaN,Surat,Gujarat,394210.0,IN,NaN,False,NaN,NaN
3631,3631,S02-1006261-5356758,04-28-22,Shipped,Amazon,Non-Amazon,Standard,JNE2305,JNE2305-KR-533-L,kurta,...,NaN,NaN,Surat,Gujarat,394210.0,IN,NaN,False,NaN,NaN
3636,3636,S02-6828927-1180856,04-28-22,Shipped,Amazon,Non-Amazon,Standard,JNE2305,JNE2305-KR-533-XXL,kurta,...,NaN,NaN,Surat,Gujarat,394210.0,IN,NaN,False,NaN,NaN
11160,11160,403-4106553-1691525,04-23-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,J0013,J0013-SKD-XXXL,Set,...,INR,5495.0,JALANDHAR,PUNJAB,144022.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,True,Easy Ship,NaN
17338,17338,403-2332292-9207530,04-20-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE2265,JNE2265-KR-501-XXL,kurta,...,INR,1316.0,NEW DELHI,DELHI,110063.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN

In [ ]:
"""
we can use all kinds of expression >, <, <=, >=, !=, &, |
loc
iloc
boolean indexing 
isin function
"""

### Data Filter

operations: | or, & and, ~ not

**Boolean Indexing:** is a data filtering technique that uses an array of True and False values (a mask) to select the specific elements from the data structures like.